### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by nicruo** [githubschool-nicruo/caption-this#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by bruno-antunes-galp-com** [comment]
teste

**Comment by airtonqueiroga** [comment]
Bom dia

**Comment by andredias-galp** [comment]
Hi

**Comment by tiagomnogueira** [comment]
Hello

**Comment by 66520530** [comment]
Hello world

**Comment by anaoliveiragalp** [comment]
hello

**Comment by galpos** [comment]
ping
